=== dekkoumi/DWWM/Web/XML/lesDisques.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT discotheque (disque+)>
<!ELEMENT disque (titre, annee?, label?, artiste*)>

	<!ELEMENT titre (#PCDATA)>
	<!ELEMENT annee (#PCDATA)>
	<!ELEMENT label (#PCDATA)>
	<!ELEMENT artiste (#PCDATA)>
<!ATTLIST disque support (CDPirate|mp3|K7Vidéo|MiniDisc|CD|CDCompil|CDLive|DVD) #REQUIRED>

=== dekkoumi/DWWM/Web/XML/discotheque.xml
<?xml version="1.0" encoding="ISO-8859-1"  standalone="no"?>
<!DOCTYPE discotheque SYSTEM "lesDisques.dtd">

<discotheque>
  <disque support="MiniDisc">
    <titre>First rays of the new rising sun</titre>
    <annee>1997</annee>
    <label>MCA Records</label>
    <artiste>Jimi HENDRIX</artiste>
  </disque>
  <disque support="CD">
    <titre>Axis : Bold as love</titre>
    <annee>1967</annee>
    <label>MCA Records</label>
    <artiste>Jimi HENDRIX</artiste>
  </disque>
  <disque support="CD">
    <titre>Are you experienced ?</titre>
    <annee>1967</annee>
    <label>MCA Records</label>
    <artiste>Jimi HENDRIX</artiste>
  </disque>
  <disque support="CD">
    <titre>Electric Ladyland</titre>
    <annee>1968</annee>
    <label>MCA Records</label>
    <artiste>Jimi HENDRIX</artiste>
  </disque>
  <disque support="CDCompil">
    <titre>Synth'axe</titre>
    <annee>1992</annee>
    <label>Digital Concept</label>
    <artiste>Sébastien PASTORE</artiste>
    <artiste>Bernard WEADLING</artiste>
    <artiste>Olivier RONGIONE</artiste>
    <artiste>Vianney TAUFOUR</artiste>
    <artiste>Anthea</artiste>
    <artiste>Eric BESSE</artiste>
    <artiste>Jean-Luc VALTEAU</artiste>
    <artiste>Nick WALD</artiste>
    <artiste>Joakim YAMA</artiste>
    <artiste>Ludovic GOMBERT</artiste>
  </disque>
  <disque support="CDCompil">
    <titre>Greatest Hits</titre>
    <annee>1967</annee>
    <label>Sony Music</label>
    <artiste>Bob DYLAN</artiste>
  </disque>
  <disque support="CD">
    <titre>Supernatural</titre>
    <annee>1975</annee>
    <label>Sony Music</label>
    <artiste>Santana</artiste>
  </disque>
  <disque support="CD">
    <titre>Infidels</titre>
    <annee>1983</annee>
    <label>Sony Music</label>
    <artiste>Bob DYLAN</artiste>
  </disque>
  <disque support="CD">
    <titre>Street Legal</titre>
    <annee>1978</annee>
    <label>Sony Music</label>
    <artiste>Bob DYLAN</artiste>
  </disque>
  <disque support="CD">
    <titre>Paul Simon</titre>
    <annee>1972</annee>
    <label>Warner Bros. Records</label>
    <artiste>Paul SIMON</artiste>
  </disque>
  <disque support="CDCompil">
    <titre>Pluriel</titre>
    <annee>2000</annee>
    <label>Sony Music</label>
    <artiste>Jean-Jacques GOLDMAN</artiste>
    <artiste>Carol FREDERICKS</artiste>
    <artiste>Michael JONES</artiste>
  </disque>
  <disque support="CD">
    <titre>The boys from Yesterday (CD 2)</titre>
    <annee>1994</annee>
    <label>Cocomelos Records</label>
    <artiste>Eagles</artiste>
  </disque>
  <disque support="CD">
    <titre>Supernatural</titre>
    <annee>1999</annee>
    <label>Arista Records</label>
    <artiste>Carlos SANTANA</artiste>
    <artiste>Dave MATTHEWS</artiste>
    <artiste>Everlast</artiste>
    <artiste>Rob THOMAS</artiste>
    <artiste>Lauryn HILL</artiste>
    <artiste>Cee-Lo</artiste>
    <artiste>Mana</artiste>
    <artiste>Eagle-Eye CHERRY</artiste>
    <artiste>Eric CLAPTON</artiste>
  </disque>
  <disque support="CD">
    <titre>White eagle</titre>
    <annee>1982</annee>
    <label>Virgin</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Johannes SCHMOELLING</artiste>
  </disque>
  <disque support="CDCompil">
    <titre>Remember Cat Stevens</titre>
    <annee>1999</annee>
    <label>Universal - Island Records</label>
    <artiste>Cat STEVENS</artiste>
  </disque>
  <disque support="CDCompil">
    <titre>The best of Kansas</titre>
    <annee>1984</annee>
    <label>Corn &amp; Blood</label>
    <artiste>Kansas</artiste>
  </disque>
  <disque support="CDCompil">
    <titre>Master Serie - Serge GAINSBOURG (vol. 3)</titre>
    <annee>1990</annee>
    <label>Polygram</label>
    <artiste>Serge GAINSBOURG</artiste>
  </disque>
  <disque support="CD">
    <titre>Tyger</titre>
    <annee>1987</annee>
    <label>Jive</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Paul HASLINGER</artiste>
  </disque>
  <disque support="CD">
    <titre>Underwater sunlight</titre>
    <annee>1986</annee>
    <label>Jive</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Paul HASLINGER</artiste>
  </disque>
  <disque support="CD">
    <titre>Force majeure</titre>
    <annee>1979</annee>
    <label>Virgin Records</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Steve JOLIFFE</artiste>
    <artiste>Klaus KRIEGER</artiste>
  </disque>
  <disque support="CD">
    <titre>Oasis</titre>
    <annee>1997</annee>
    <label>TDI Music International</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Jerome FROESE</artiste>
    <artiste>Zlatko PERIKA</artiste>
  </disque>
  <disque support="CD">
    <titre>Goblin's club</titre>
    <annee>1996</annee>
    <label>Tadream Music</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Jerome FROESE</artiste>
    <artiste>Linda SPA</artiste>
  </disque>
  <disque support="CD">
    <titre>Green desert</titre>
    <annee>1973</annee>
    <label>Tadream Music Production</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Peter BAUMANN</artiste>
  </disque>
  <disque support="CD">
    <titre>Rubycon</titre>
    <annee>1975</annee>
    <label>Virgin Records</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Peter BAUMANN</artiste>
  </disque>
  <disque support="CD">
    <titre>Atem</titre>
    <annee>1973</annee>
    <label>Tadream Music Production</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Peter BAUMANN</artiste>
  </disque>
  <disque support="CD">
    <titre>Zeit</titre>
    <annee>1972</annee>
    <label>Jive</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Peter BAUMANN</artiste>
    <artiste>Florian FRICKE</artiste>
  </disque>
  <disque support="CD">
    <titre>Pergamon</titre>
    <annee>1980</annee>
    <label>Tadream Music Production</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Johannes SCHMOELLING</artiste>
  </disque>
  <disque support="CD">
    <titre>Poland</titre>
    <annee>1984</annee>
    <label>Tadream Music Production</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Johannes SCHMOELLING</artiste>
  </disque>
  <disque support="CD">
    <titre>Le parc</titre>
    <annee>1985</annee>
    <label>Tadream Music Production</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Johannes SCHMOELLING</artiste>
  </disque>
  <disque support="CD">
    <titre>Lily on the beach</titre>
    <annee>1989</annee>
    <label>Private</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Paul HASLINGER</artiste>
  </disque>
  <disque support="CD">
    <titre>Tangram</titre>
    <annee>1980</annee>
    <label>Virgin Records</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Johannes SCHMOELLING</artiste>
  </disque>
  <disque support="CD">
    <titre>Encore</titre>
    <annee>1977</annee>
    <label>Virgin Records</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Peter BAUMANN</artiste>
  </disque>
  <disque support="CD">
    <titre>Stratosfear</titre>
    <annee>1976</annee>
    <label>Virgin Music</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Peter BAUMANN</artiste>
  </disque>
  <disque support="CD">
    <titre>Rockoon</titre>
    <annee>1992</annee>
    <label>Tadream Music</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Jerome FROESE</artiste>
    <artiste>Zlatko PERIKA</artiste>
  </disque>
  <disque support="CD">
    <titre>Logos</titre>
    <annee>1983</annee>
    <label>Hansa</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Paul HASLINGER</artiste>
  </disque>
  <disque support="CD">
    <titre>Optical Race</titre>
    <annee>1988</annee>
    <label>Private</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Paul HASLINGER</artiste>
  </disque>
  <disque support="CDLive">
    <titre>Live miles</titre>
    <annee>1988</annee>
    <label>Tadream Music Production</label>
    <artiste>Tangerine Dream</artiste>
    <artiste>Edgar FROESE</artiste>
    <artiste>Chris FRANKE</artiste>
    <artiste>Paul HASLINGER</artiste>
  </disque>
  <disque support="CD">
    <titre>La musique des films</titre>
    <annee>1996</annee>
    <label>Virgin France</label>
    <artiste>Eric SERRA</artiste>
    <artiste>Arthur SIMMS</artiste>
    <artiste>Vanessa PARADIS</artiste>
    <artiste>Noa</artiste>
    <artiste>Rupert HINE</artiste>
  </disque>
  <disque support="CD">
    <titre>Atlantis</titre>
    <annee>1991</annee>
    <label>Edition la Marguerite</label>
    <artiste>Eric SERRA</artiste>
    <artiste>Vanessa PARADIS</artiste>
  </disque>
  <disque support="CD">
    <titre>Le mage de Boheme</titre>
    <annee>1991</annee>
    <label>Jupiter</label>
    <artiste>Claude GALLENCA</artiste>
  </disque>
  <disque support="CD">
    <titre>Mosaïque</titre>
    <annee>1993</annee>
    <label>Jupiter</label>
